ALTER TABLE `OpenaiBot`
ADD COLUMN `responseFormat` VARCHAR(20) NULL DEFAULT 'text',
ADD COLUMN `ttsModel` VARCHAR(100) NULL,
ADD COLUMN `ttsVoice` VARCHAR(100) NULL;

ALTER TABLE `OpenaiSetting`
ADD COLUMN `responseFormat` VARCHAR(20) NULL DEFAULT 'text',
ADD COLUMN `ttsModel` VARCHAR(100) NULL,
ADD COLUMN `ttsVoice` VARCHAR(100) NULL;
